// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {realtime} from '../models';

export function ClearCookies():Promise<domain.WorkspaceState>;

export function CreateCollection(arg1:string):Promise<domain.WorkspaceState>;

export function CreateEnvironment(arg1:string):Promise<domain.WorkspaceState>;

export function CreateResponseVariable(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<domain.WorkspaceState>;

export function DebugRequestVariables(arg1:domain.Request,arg2:string,arg3:Array<domain.KeyValue>):Promise<domain.VariableDebugReport>;

export function DebugVariables(arg1:string,arg2:Array<domain.KeyValue>):Promise<domain.VariableDebugReport>;

export function DeleteCollection(arg1:string):Promise<domain.WorkspaceState>;

export function DeleteCookie(arg1:domain.Cookie):Promise<domain.WorkspaceState>;

export function DeleteEnvironment(arg1:string):Promise<domain.WorkspaceState>;

export function DeleteRequest(arg1:string):Promise<domain.WorkspaceState>;

export function ExportHARCollection(arg1:string):Promise<string>;

export function ExportOpenAPICollection(arg1:string):Promise<string>;

export function ExportPostmanCollection(arg1:string):Promise<string>;

export function ExportPostmanRequest(arg1:domain.Request,arg2:string):Promise<string>;

export function FormatBody(arg1:string,arg2:string):Promise<string>;

export function GetState():Promise<domain.WorkspaceState>;

export function ImportCurlRequest(arg1:string,arg2:string):Promise<domain.WorkspaceState>;

export function ImportFetchRequest(arg1:string,arg2:string):Promise<domain.WorkspaceState>;

export function ImportHARCollection(arg1:string):Promise<domain.WorkspaceState>;

export function ImportOpenAPICollection(arg1:string):Promise<domain.WorkspaceState>;

export function ImportOpenAPICollectionWithOptions(arg1:string,arg2:domain.OpenAPIImportOptions):Promise<domain.WorkspaceState>;

export function ImportPostmanCollection(arg1:string):Promise<domain.WorkspaceState>;

export function InspectOpenAPI(arg1:string):Promise<domain.OpenAPIInfo>;

export function PreviewRequest(arg1:domain.Request,arg2:string,arg3:Array<domain.KeyValue>):Promise<domain.PreparedRequest>;

export function QueryJSONPath(arg1:string,arg2:string):Promise<string>;

export function RunCollection(arg1:string,arg2:string,arg3:number):Promise<domain.RunnerResult>;

export function SaveCollection(arg1:domain.Collection):Promise<domain.WorkspaceState>;

export function SaveEnvironment(arg1:domain.Environment):Promise<domain.WorkspaceState>;

export function SaveGlobals(arg1:Array<domain.KeyValue>):Promise<domain.WorkspaceState>;

export function SaveRequest(arg1:domain.Request):Promise<domain.WorkspaceState>;

export function SaveRunnerResult(arg1:domain.RunnerResult):Promise<domain.WorkspaceState>;

export function SaveSettings(arg1:domain.Settings):Promise<domain.WorkspaceState>;

export function SaveTextFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectFile():Promise<string>;

export function SendRequest(arg1:domain.Request,arg2:string,arg3:Array<domain.KeyValue>):Promise<domain.Response>;

export function SetActiveEnvironment(arg1:string):Promise<domain.WorkspaceState>;

export function TestSSE(arg1:realtime.SSERequest,arg2:string,arg3:Array<domain.KeyValue>):Promise<realtime.SSEResult>;

export function TestVariable(arg1:domain.KeyValue,arg2:string,arg3:Array<domain.KeyValue>):Promise<string>;

export function TestWebSocket(arg1:realtime.WebSocketRequest,arg2:string,arg3:Array<domain.KeyValue>):Promise<realtime.WebSocketResult>;
