// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCookies() {
  return window['go']['main']['App']['ClearCookies']();
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateEnvironment(arg1) {
  return window['go']['main']['App']['CreateEnvironment'](arg1);
}

export function CreateResponseVariable(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateResponseVariable'](arg1, arg2, arg3, arg4, arg5);
}

export function DebugRequestVariables(arg1, arg2, arg3) {
  return window['go']['main']['App']['DebugRequestVariables'](arg1, arg2, arg3);
}

export function DebugVariables(arg1, arg2) {
  return window['go']['main']['App']['DebugVariables'](arg1, arg2);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteCookie(arg1) {
  return window['go']['main']['App']['DeleteCookie'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function DeleteRequest(arg1) {
  return window['go']['main']['App']['DeleteRequest'](arg1);
}

export function ExportHARCollection(arg1) {
  return window['go']['main']['App']['ExportHARCollection'](arg1);
}

export function ExportOpenAPICollection(arg1) {
  return window['go']['main']['App']['ExportOpenAPICollection'](arg1);
}

export function ExportPostmanCollection(arg1) {
  return window['go']['main']['App']['ExportPostmanCollection'](arg1);
}

export function ExportPostmanRequest(arg1, arg2) {
  return window['go']['main']['App']['ExportPostmanRequest'](arg1, arg2);
}

export function FormatBody(arg1, arg2) {
  return window['go']['main']['App']['FormatBody'](arg1, arg2);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ImportCurlRequest(arg1, arg2) {
  return window['go']['main']['App']['ImportCurlRequest'](arg1, arg2);
}

export function ImportFetchRequest(arg1, arg2) {
  return window['go']['main']['App']['ImportFetchRequest'](arg1, arg2);
}

export function ImportHARCollection(arg1) {
  return window['go']['main']['App']['ImportHARCollection'](arg1);
}

export function ImportOpenAPICollection(arg1) {
  return window['go']['main']['App']['ImportOpenAPICollection'](arg1);
}

export function ImportOpenAPICollectionWithOptions(arg1, arg2) {
  return window['go']['main']['App']['ImportOpenAPICollectionWithOptions'](arg1, arg2);
}

export function ImportPostmanCollection(arg1) {
  return window['go']['main']['App']['ImportPostmanCollection'](arg1);
}

export function InspectOpenAPI(arg1) {
  return window['go']['main']['App']['InspectOpenAPI'](arg1);
}

export function PreviewRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewRequest'](arg1, arg2, arg3);
}

export function QueryJSONPath(arg1, arg2) {
  return window['go']['main']['App']['QueryJSONPath'](arg1, arg2);
}

export function RunCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCollection'](arg1, arg2, arg3);
}

export function SaveCollection(arg1) {
  return window['go']['main']['App']['SaveCollection'](arg1);
}

export function SaveEnvironment(arg1) {
  return window['go']['main']['App']['SaveEnvironment'](arg1);
}

export function SaveGlobals(arg1) {
  return window['go']['main']['App']['SaveGlobals'](arg1);
}

export function SaveRequest(arg1) {
  return window['go']['main']['App']['SaveRequest'](arg1);
}

export function SaveRunnerResult(arg1) {
  return window['go']['main']['App']['SaveRunnerResult'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTextFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2, arg3);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SendRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2, arg3);
}

export function SetActiveEnvironment(arg1) {
  return window['go']['main']['App']['SetActiveEnvironment'](arg1);
}

export function TestSSE(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestSSE'](arg1, arg2, arg3);
}

export function TestVariable(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestVariable'](arg1, arg2, arg3);
}

export function TestWebSocket(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestWebSocket'](arg1, arg2, arg3);
}
