// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {realtime} from '../models';

export function CreateCollection(arg1:string):Promise<domain.WorkspaceState>;

export function DeleteCollection(arg1:string):Promise<domain.WorkspaceState>;

export function DeleteRequest(arg1:string):Promise<domain.WorkspaceState>;

export function ExportPostmanCollection(arg1:string):Promise<string>;

export function FormatBody(arg1:string,arg2:string):Promise<string>;

export function GetState():Promise<domain.WorkspaceState>;

export function ImportCurlRequest(arg1:string,arg2:string):Promise<domain.WorkspaceState>;

export function ImportFetchRequest(arg1:string,arg2:string):Promise<domain.WorkspaceState>;

export function ImportPostmanCollection(arg1:string):Promise<domain.WorkspaceState>;

export function RunCollection(arg1:string,arg2:string,arg3:number):Promise<domain.RunnerResult>;

export function SaveCollection(arg1:domain.Collection):Promise<domain.WorkspaceState>;

export function SaveEnvironment(arg1:domain.Environment):Promise<domain.WorkspaceState>;

export function SaveGlobals(arg1:Array<domain.KeyValue>):Promise<domain.WorkspaceState>;

export function SaveRequest(arg1:domain.Request):Promise<domain.WorkspaceState>;

export function SendRequest(arg1:domain.Request,arg2:string,arg3:Array<domain.KeyValue>):Promise<domain.Response>;

export function SetActiveEnvironment(arg1:string):Promise<domain.WorkspaceState>;

export function TestSSE(arg1:realtime.SSERequest,arg2:string,arg3:Array<domain.KeyValue>):Promise<realtime.SSEResult>;

export function TestWebSocket(arg1:realtime.WebSocketRequest,arg2:string,arg3:Array<domain.KeyValue>):Promise<realtime.WebSocketResult>;
