// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteRequest(arg1) {
  return window['go']['main']['App']['DeleteRequest'](arg1);
}

export function ExportPostmanCollection(arg1) {
  return window['go']['main']['App']['ExportPostmanCollection'](arg1);
}

export function FormatBody(arg1, arg2) {
  return window['go']['main']['App']['FormatBody'](arg1, arg2);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ImportCurlRequest(arg1, arg2) {
  return window['go']['main']['App']['ImportCurlRequest'](arg1, arg2);
}

export function ImportFetchRequest(arg1, arg2) {
  return window['go']['main']['App']['ImportFetchRequest'](arg1, arg2);
}

export function ImportPostmanCollection(arg1) {
  return window['go']['main']['App']['ImportPostmanCollection'](arg1);
}

export function RunCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCollection'](arg1, arg2, arg3);
}

export function SaveCollection(arg1) {
  return window['go']['main']['App']['SaveCollection'](arg1);
}

export function SaveEnvironment(arg1) {
  return window['go']['main']['App']['SaveEnvironment'](arg1);
}

export function SaveGlobals(arg1) {
  return window['go']['main']['App']['SaveGlobals'](arg1);
}

export function SaveRequest(arg1) {
  return window['go']['main']['App']['SaveRequest'](arg1);
}

export function SendRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2, arg3);
}

export function SetActiveEnvironment(arg1) {
  return window['go']['main']['App']['SetActiveEnvironment'](arg1);
}

export function TestSSE(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestSSE'](arg1, arg2, arg3);
}

export function TestWebSocket(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestWebSocket'](arg1, arg2, arg3);
}
